# Generated by Django 3.2 on 2021-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Country_of_Origin',
            new_name='Title_in_Original_Language',
        ),
        migrations.AddField(
            model_name='post',
            name='Submission_City',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
