# Generated by Django 3.2 on 2021-04-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
